// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBUe-f4tH2sfurt-q6xwNJQdmw6MItY8s',
    appId: '1:624162048996:web:165fbb06905d204fad55f1',
    messagingSenderId: '624162048996',
    projectId: 'campusbuzz-accounts',
    authDomain: 'campusbuzz-accounts.firebaseapp.com',
    storageBucket: 'campusbuzz-accounts.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhE0q2rIuIBUUSrldybDOSfCG05oNbJ58',
    appId: '1:624162048996:android:61d925f2b0968829ad55f1',
    messagingSenderId: '624162048996',
    projectId: 'campusbuzz-accounts',
    storageBucket: 'campusbuzz-accounts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkfcP2EyJkgSA0gSgNzC50K9yUtYUcpfI',
    appId: '1:624162048996:ios:4b760bd0ddeeddedad55f1',
    messagingSenderId: '624162048996',
    projectId: 'campusbuzz-accounts',
    storageBucket: 'campusbuzz-accounts.appspot.com',
    iosClientId: '624162048996-fcvqrofgp1mv5pbp7uckni4pcs2l30kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusbuzzAccounts',
  );
}
